### ISSUE TITLE
yarn install

### ISSUE THREAD

**Issue by sintoris** [gabyx/TechnicalMarkdown#13]
Following the instructions, after cloning the project and running `yarn install` the result is `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`

**Comment by gabyx** [comment]
Really :-) ok.

**Comment by gabyx** [comment]
Have a look.

**Comment by gabyx** [comment]
Solution:
https://stackoverflow.com/a/47680012/293195

**Comment by gabyx** [comment]
You are not using "yarn" but something else...

**Comment by gabyx** [comment]
https://github.com/Joystream/helpdesk/issues/16#issuecomment-484966596

**Comment by sintoris** [comment]
Indeed! "yarn - scenario testing of Unix command line tools"

Thanks!

**Comment by gabyx** [comment]
I had the same shitty trouble once...
